### ISSUE TITLE
Criar MVP do projeto

### ISSUE THREAD

**Issue by ezanattatray** [Tray-FrontEnd/MagicOP#1]
#### O MVP do projeto, deve conter as seguintes funções:

- [x] Instalar o ambiente do OpenCode(GEM e Gulp) **=> magicop install opencode**

- [x] ~~Instalar dependências do OpenCode **=> magicop install depends**~~
  - [x] ~~Ruby~~
  - [x] ~~GEM~~
  - [x] ~~Node.JS~~
  - [x] ~~NPM~~

- [x] Edição rápida de um tema existente **=> magicop edit {{STORE_ID}} {{API_KEY}} {{API_PASSWORD}} {{THEME_ID}}**

- [x] Work para executar watch e gulp simultaneamente **=> magicop work**

- [x] Finalizar função work ou qualquer instância da gem ou do gulp **=> magicop stop**

**Comment by lkusunoki** [comment]
E se for __magicop install full__?

**Comment by ezanattatray** [comment]
deixei como **magicop install depends** pois full da ideia que o opencode vai ser instalado também, onde a função,apenas instala as dependências

**Comment by ezanattatray** [comment]
**magicop install depends** ficará para ser implementado em uma **versão futura**, pois é preciso definir com mais detalhes, como instalar cada pacote no Ubuntu.

**Comment by ezanattatray** [comment]
Todas as funções foram implementadas no pull request #3
